### PR TITLE
Change LICENSE to AGPLv3

### PR DESCRIPTION
**Pull request by berendt**
Closes osism/openstack-image-manager#663

### CODE REVIEW

**Comment by berendt** [comment]
@fkr @garloff

**Comment by fkr** [comment]
Relicensing to AGPLv3 would solve the issue in #663 - at least if I understand [this](https://www.gnu.org/licenses/license-compatibility.html) document correctly:

> The ordinary GNU General Public License and the GNU Affero General Public License are two different copyleft licenses, so they are naturally incompatible. We have set up a special kind of explicit compatibility between them: you can include source code under the GNU GPL version 3 together with other source code under the GNU Affero GPL in a single combined program. This is permitted because both of those licenses explicitly say so, and the effect is that the GNU AGPL applies to the combined program.

However the usual IANAL applies.

**Review by fkr — COMMENTED** [review]
I'm not really sure, wether I can assess wether the relicensing can take place, since I'm not sure wether all (substantial) contributors have waived their rights to do this or need to be asked.

**Comment by berendt** [comment]
We should have a process for how we do this with SCS projects. Which team can we best bring this to?

**Comment by fkr** [comment]
> I'm not really sure, wether I can assess wether the relicensing can take place, since I'm not sure wether all (substantial) contributors have waived their rights to do this or need to be asked.

I did some more research on this and while the IANAL still applies, my opinion is as follows:

The license change from a permissive (ASL-2) license to AGPLv3 is possible *without* involving the other (substantial contributors) as long as the new license still complies with the minimal requirements of the (permissive) license.

As to @berendt's question: 

> We should have a process for how we do this with SCS projects. Which team can we best bring this to?

PB is the best place atm.

**Comment by berendt** [comment]
Let's discuss & document this in the next PB.

**Pull request closed without merging**
