### PR TITLE
add --verifyurls to check.py

### LINKED ISSUE #304: [feat] check for valid url targets
I would like to be able to pre-flight check whether the URLs in the images.yml are still valid and can be downloaded or raise an error if they are unavailable.

Thus I would suggest that  [check.py](https://github.com/osism/openstack-image-manager/blob/0267b450749f394221bfdff3b3cb2a9b66f141ea/src/check.py#L32) should raise an error on r.status_code so one can act upon invalid URL definitions

comments?

ralf

### PR DESCRIPTION
**Pull request by frosty-geek**
this raises an error on failed urls and reports back the count of failures

Closes #304
Duplicate of #320

Signed-off-by: Ralf Heiringhoff <ralf.heiringhoff@plusserver.com>

### CODE REVIEW

**Comment by frosty-geek** [comment]
I'm fine with going with #320 i just wanted to contribute what i've prepared before noticing the other PR.

**Comment by berendt** [comment]
Let's merge #320 first and check if anything from this one can be added afterwards. Thank you for sharing anyways.

**Comment by berendt** [comment]
@frosty-geek #320. Can you test Can you can test whether this is sufficient for you?

**Comment by frosty-geek** [comment]
@berendt i'm trying to "confine" openstack-image-manager into a Docker container atm (similar to osism/docker-image-openstackclient) so I can use it via "timed Jenkins cronjobs", but tox is giving me a really hard time. 

From my preliminary tests the major difference between this and #320 was the ability to test for the remote urls separately. I would prefer to have a way to check for dead urls somehow somewhere, but I guess it's a design decision whether the config creator (@costelter is working on a cloud-image-crawler with debian+ubuntu working atm) should check it or the openstack-image-manager. 

So I'm going to close this pull request and would amend to the changes made by #320 if necessary.

PS: cloud-image-crawler will be made available as open source  after @costelter's vacation, it's a rough working example atm.

**Comment by berendt** [comment]
@frosty-geek I think it makes sense to add the Containerfile to this repository itself. Like with python-osism.

**Pull request closed without merging**
